import { ProcessorDto, ReceivingCardDto, ConverterDto } from '../dto';

// Datos de ejemplo de procesadores disponibles
export const NOVASTAR_PROCESSORS: ProcessorDto[] = [
  {
    id: 'novastar-vx4s',
    name: 'NovaStar VX4S',
    brand: 'NovaStar',
    model: 'VX4S',
    maxInputsHDMI: 4,
    maxInputsDP: 2,
    maxOutputs: 512,
    maxPixels: 1920000,
    supportedResolutions: ['1080p', '2K', '4K'],
    frameRates: [50, 60],
    bitDepths: [8, 10, 12],
    cost: 8500,
    features: ['ScalerInput', 'Backup', 'Redundancy'],
    specifications: {
      weight: 5.2,
      power: 200,
      dimensions: '320x180x90mm',
    },
  },
  {
    id: 'novastar-vx2pro',
    name: 'NovaStar VX2 Pro',
    brand: 'NovaStar',
    model: 'VX2 Pro',
    maxInputsHDMI: 2,
    maxInputsDP: 2,
    maxOutputs: 256,
    maxPixels: 960000,
    supportedResolutions: ['1080p', '2K'],
    frameRates: [50, 60],
    bitDepths: [8, 10],
    cost: 5500,
    features: ['Backup'],
    specifications: {
      weight: 3.5,
      power: 150,
      dimensions: '250x150x80mm',
    },
  },
];

export const BROMPTON_PROCESSORS: ProcessorDto[] = [
  {
    id: 'brompton-hdr',
    name: 'Brompton Tessera SX40',
    brand: 'Brompton',
    model: 'SX40',
    maxInputsHDMI: 4,
    maxInputsDP: 2,
    maxOutputs: 4,
    maxPixels: 4096000,
    supportedResolutions: ['4K', '8K'],
    frameRates: [50, 60, 120, 240],
    bitDepths: [8, 10, 12],
    cost: 12000,
    features: ['ULL', 'Failover', 'Redundancy', 'HDR'],
    specifications: {
      weight: 4.8,
      power: 250,
      dimensions: '330x190x95mm',
    },
  },
  {
    id: 'brompton-multi-viewer',
    name: 'Brompton Tessera M4',
    brand: 'Brompton',
    model: 'M4',
    maxInputsHDMI: 4,
    maxInputsDP: 2,
    maxOutputs: 4,
    maxPixels: 2048000,
    supportedResolutions: ['2K', '4K'],
    frameRates: [50, 60, 120],
    bitDepths: [8, 10, 12],
    cost: 9500,
    features: ['Failover', 'Redundancy'],
    specifications: {
      weight: 4.2,
      power: 200,
      dimensions: '320x180x90mm',
    },
  },
];

export const RECEIVING_CARDS: ReceivingCardDto[] = [
  {
    id: 'card-hdmi-input',
    name: 'HDMI Input Card',
    type: 'input',
    processorBrand: 'NovaStar',
    connectorType: 'HDMI',
    maxChannels: 2,
    cost: 300,
    specifications: { resolution: '4K60' },
  },
  {
    id: 'card-dp-input',
    name: 'DisplayPort Input Card',
    type: 'input',
    processorBrand: 'NovaStar',
    connectorType: 'DP',
    maxChannels: 2,
    cost: 400,
    specifications: { resolution: '8K60' },
  },
  {
    id: 'card-rj45-output',
    name: 'RJ45 Output Card',
    type: 'output',
    processorBrand: 'NovaStar',
    connectorType: 'RJ45',
    cost: 200,
    specifications: { maxDistance: '100m' },
  },
  {
    id: 'card-fiber-output',
    name: 'Optical Fiber Output Card',
    type: 'output',
    processorBrand: 'Brompton',
    connectorType: 'OpticalFiber',
    cost: 800,
    specifications: { maxDistance: '2000m', bandwidth: '10Gbps' },
  },
  {
    id: 'card-backup',
    name: 'Backup Input Card',
    type: 'auxiliary',
    processorBrand: 'NovaStar',
    connectorType: 'HDMI',
    cost: 150,
    specifications: { autoSwitching: true },
  },
];

export const CONVERTERS: ConverterDto[] = [
  {
    id: 'converter-hdmi-dp',
    name: 'HDMI to DisplayPort Converter',
    inputType: 'HDMI',
    outputType: 'DP',
    brand: 'Generic',
    cost: 250,
    specifications: { resolution: '4K60' },
  },
  {
    id: 'converter-dp-rj45',
    name: 'DisplayPort to RJ45 Converter',
    inputType: 'DP',
    outputType: 'RJ45',
    brand: 'NovaStar',
    cost: 400,
    specifications: { resolution: '4K60', distance: '100m' },
  },
];
