version: '3.8'

services:
  alfalite-database:
    image: postgres:15-alpine
    container_name: alfalite-database-dev
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_ADMIN_USER}
      - POSTGRES_PASSWORD=${DB_ADMIN_PASSWORD}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432" # Expuesto para que pueda conectarme con DBeaver/PgAdmin
    restart: unless-stopped
  mailhog:
    image: mailhog/mailhog:latest
    container_name: alfalite-mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI
    restart: unless-stopped

volumes:
  postgres_data_dev:

networks:
  default:
    name: alfalite-dev-network